### ISSUE TITLE
Unable to insert link in richeditor

### ISSUE THREAD

**Issue by bachvtuan** [wintercms/wn-pages-plugin#40] opened 2023-11-09 10:45 UTC
- Winter CMS Build:  1.2.3
- Pages Plugin Version: 2.1.2
- PHP Version: 8.1.16

### Description:
Unable to insert link to selected text

### Steps To Reproduce:
1. Select any static page( The select page must define richeditor varriable)
2. Input texts to the richtexteditor
3. First try is succesfull
4. Second time or later are unable to input thel ink because the input link modal is closed immediately.

Attached the screencast:

https://github.com/wintercms/wn-pages-plugin/assets/2065400/bd36f065-9db9-4564-b907-5c07951eb651

**Comment by LukeTowers** [comment] 2023-11-09 14:40
Duplicate of #35, fixed by https://github.com/wintercms/winter/commit/23ba829f19e6062932f61efb390e36c91b8bc497. Will try to release 1.2.4 of Winter soon, but in the meantime you can switch to dev-develop in your composer.json

**Closed by LukeTowers** 2023-11-09 14:40 UTC
Labels: Type: Unconfirmed Bug, Status: Review Needed

**Comment by AIC-BV** [comment] 2023-11-21 07:50
@bachvtuan is this fixed for you?

**Comment by bachvtuan** [comment] 2023-11-21 07:57
@AIC-BV I haven't tried that. I'm still waiting for the next WinterCMS release. Meanwhile, I copied 2 js files from this commit https://github.com/wintercms/winter/commit/23ba829f19e6062932f61efb390e36c91b8bc497 and it works

**Comment by AIC-BV** [comment] 2023-11-21 08:01
Oh I see it, I don't use richeditor, I have multilingual richeditor which probably has the same issue, thx for the reply!
